import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'Kurdish (Sorani)' | 'English' | 'Arabic';
type Theme = 'dark' | 'light';

interface ThemeLanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  'English': {
    // ... (keep all your existing English keys from before)
    lostItems: 'Lost items',
    foundItems: 'Found items',
    howItWorks: 'How it works',
    successStories: 'Success stories',
    signIn: 'Sign in',
    getStarted: 'Get started',
    heroTitle: 'Reuniting you with what matters most',
    heroSubtitle: "The world's most sophisticated network for lost and found. Fast, secure, and precision-engineered for modern discovery.",
    reportLost: 'Report a lost item',
    foundSomething: 'I found something',
    searchPlaceholder: 'Search for a lost or found item...',
    searchButton: 'Search',
    browseCategory: 'Browse by category',
    whatAreYouLookingFor: 'What are you looking for?',
    jumpStraight: 'Jump straight to the category that matches your item.',
    viewAll: 'View all',
    recentlyFound: 'Recently found',
    oneOfTheseYours: 'Is one of these yours?',
    kindPeople: 'Kind people found these items and are waiting to return them.',
    itemsReunited: 'Items reunited',
    members: 'Members',
    activeListings: 'Active listings',
    reunionRate: 'Reunion rate',
    realReunions: 'Real reunions, real relief',
    peopleReconnect: 'People reconnect with what they thought was gone for good.',
    isDozerFree: 'Is Bdozawa free to use?',
    isDozerFreeDesc: 'Yes, Reporting lost or found items and connecting with people is completely free. Rewards are optional and set entirely by the person who lost the item.',
    howKeepSafe: 'How do you keep my information safe?',
    howKeepSafeDesc: 'We use advanced encryption and privacy controls to ensure your contact details are shared only when you choose to connect.',
    whatDoBefore: 'What should I do before meeting someone?',
    whatDoBeforeDesc: 'Always meet in a public, well-lit place and verify item details before handing anything over.',
    lostSomethingTitle: 'Lost something? Let\'s bring it home.',
    lostSomethingSubtitle: 'Join a community that believes in giving things back. Post your first listing in under a minute.',
    reportAnItem: 'Report an item',
    browseItems: 'Browse items',
    footerTagline: 'The trusted way to reunite people with what they\'ve lost — powered by community and smart matching.',
    product: 'Product',
    company: 'Company',
    faq: 'FAQ',
    about: 'About',
    careers: 'Careers',
    allRightsReserved: '© 2026 Bdozawa. All rights reserved.',
    
    faqTitle: 'Questions, answered',
    faqSubtitle: 'Everything you need to feel confident using Bdozawa.',
    howItWorksTitle: 'Four simple steps to a happy ending',
    howItWorksSubtitle: 'No accounts to wrestle with, no friction — just a clear path from lost to found.',
    step1Title: 'Report it',
    step1Desc: 'Add a photo and a few details. It takes less than a minute.',
    step2Title: 'Get matched',
    step2Desc: 'Our engine surfaces likely matches with a confidence score.',
    step3Title: 'Connect safely',
    step3Desc: 'Chat securely to verify ownership before meeting up.',
    step4Title: 'Reunite',
    step4Desc: 'Arrange a handoff and mark it resolved. Everyone wins.',
    
    catElectronics: 'Electronics',
    catElectronicsDesc: 'Phones, laptops, earbuds',
    catWallets: 'Wallets & Cards',
    catWalletsDesc: 'Wallets, purses, cards',
    catKeys: 'Keys',
    catKeysDesc: 'House & car keys, fobs',
    catBags: 'Bags & Luggage',
    catBagsDesc: 'Backpacks, suitcases',
    catJewelry: 'Jewelry',
    catJewelryDesc: 'Rings, watches, necklaces',
    catDocuments: 'Documents',
    catDocumentsDesc: 'IDs, passports, papers',
    catPets: 'Pets',
    catPetsDesc: 'Dogs, cats & companions',
    catClothing: 'Clothing',
    catClothingDesc: 'Jackets, hats, scarves',
    catAccessories: 'Accessories',
    catAccessoriesDesc: 'Glasses, umbrellas',
    catOther: 'Other',
    catOtherDesc: 'Everything else',

    badgeLost: 'Lost',
    badgeFound: 'Found',
    faqSmartMatch: 'How does smart matching work?',
    faqSmartMatchDesc: 'Our engine surfaces likely matches by comparing keywords, dates, and locations with a confidence score.',
    faqReward: 'Can I offer a reward?',
    faqRewardDesc: 'Yes! You can optionally attach a reward amount when reporting a lost item to encourage quick community returns.',
    story1Quote: 'I left my laptop bag near the university campus in Erbil and panicked. Mohammed Sabir helped me track down the listing on Bdozawa within the hour.',
    story1Name: 'Azad Aram',
    story1Detail: 'Reunited with equipment • Erbil',
    story2Quote: 'Found a misplaced driving license card on the street in Sulaymaniyah. Using the platform, we safely returned it to the owner the same afternoon.',
    story2Name: 'Akam Ali',
    story2Detail: 'Returned an ID card • Sulaymaniyah',
    story3Quote: 'We coordinated our project research files and lost a flash drive near the library. Arez, Akam, and Zina helped post the alert and we recovered it immediately.',
    story3Name: 'Zina Abdulla',
    story3Detail: 'Recovered project data • Duhok',

    backHome: 'Back home',
    createAccountTitle: 'Create account',
    createAccountSubtitle: 'Join Bdozawa to report and find lost items',
    orContinueWithEmail: 'or continue with email',
    fullName: 'Full name',
    email: 'Email',
    password: 'Password',
    createAccountBtn: 'Create account',
    alreadyHaveAccount: 'Already have an account?',
    rightSideTitle: 'Join the community that brings things home.',
    smartMatching: 'Smart matching',
    smartMatchingDesc: 'Find likely matches instantly',
    privateSecure: 'Private & secure',
    privateSecureDesc: 'Your details stay yours',
    trustedCommunity: 'Trusted community',
    trustedCommunityDesc: '126k+ verified members', 
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Sign in to manage your listings and messages',
    orContinueEmail: 'or continue with email',
    forgotPassword: 'Forgot password?',
    signInBtn: 'Sign in',
    magicLink: 'Email me a magic link instead',
    newHere: 'New here?',
    createAccountLink: 'Create an account',
    loginRightTitle: "Lost something? You're one step away from getting it back.",

    // NEW SEARCH & FILTER KEYS:
    searchPageTitle: 'Search items',
    searchPageSubtitle: 'Filter by type, category and keywords to find what you\'re looking for',
    searchInputPlaceholder: 'Search by title, brand, location, keyword',
    allCategories: 'All categories',
    allTypes: 'All items',
    mostRecent: 'Most recent',
    clearFilters: 'Clear filters',
    noMatchingItems: 'No matching items',
    tryAdjustingFilters: 'Try adjusting your filters or search terms',
  
    itemNotFound: 'Item not found',
itemNotFoundDesc: "The item you are looking for doesn't exist or has been removed.",
goBackSearch: 'Go back to search',
mustBeSignedIn: 'You must be signed in',
sendSecureMessage: 'Send a secure message',
introduceYourself: 'Introduce yourself and explain how you can help with this item.',
shareDetailsTip: 'Tip: share details only the true owner would know to verify ownership.',
messagePlaceholder: 'Hi, I think this might be mine...',
sendMessageBtn: 'Send message',
home: 'Home',
views: 'views',
description: 'Description',
category: 'Category',
dateLostStr: 'Date lost',
dateFoundStr: 'Date found',
colour: 'Colour',
ownerStr: 'Owner',
reports: 'Reports',
helpful: 'Helpful',
contactBtn: 'Contact',
saveBtn: 'Save',
locationStr: 'LOCATION',
clickForDirections: 'Click map for directions',
country: 'COUNTRY',
city: 'CITY',
signInToSave: 'Sign in to save listings',
oldest: 'Oldest',
searching: 'Searching...',
itemsFound: 'items found',
itemFound: 'item found',
reward: 'Reward',
justNow: 'Just now',
unknownLocation: 'Unknown location',
  },
  'Kurdish (Sorani)': {
    lostItems: 'شتە ونبووەکان',
    foundItems: 'شتە دۆزراوەکان',
    howItWorks: 'چۆن کار دەکات',
    successStories: 'چیڕۆکی سەرکەوتن',
    signIn: 'چوونەژوورەوە',
    getStarted: 'دەستپێکردن',
    heroTitle: 'گه‌ڕاندنه‌وه‌ی ئه‌و شتانه‌ی بۆت گرنگن',
    heroSubtitle: 'پێشکەوتوترین تۆڕ بۆ شتە ونبووەکان و دۆزراوەکان. خێرا، سەلامەت، و دروستکراو بۆ دۆزینەوەی مودێرن.',
    reportLost: 'ڕاپۆرتکردنی شتی ونبوو',
    foundSomething: 'شتێکم دۆزیوەتەوە',
    searchPlaceholder: 'گەڕان بەدوای شتێکی ونبوو یان دۆزراوەدا...',
    searchButton: 'گەڕان',
    browseCategory: 'گەڕان بەپێی پۆل',
    whatAreYouLookingFor: 'بەدوای چی دەگەڕێیت؟',
    jumpStraight: 'ڕاستەوخۆ بچۆ بۆ ئەو پۆلەی کە لەگەڵ شتەکەت دەگونجێت.',
    viewAll: 'بینینی هەموو',
    recentlyFound: 'تازە دۆزراوەکان',
    oneOfTheseYours: 'ئایا یەکێک لەمانە هی تۆیە؟',
    kindPeople: 'کەسانی بەزەییدار ئەم شتە دۆزراوانەیان دۆزیوەتەوە و چاوەڕێی گەڕاندنەوەیانن.',
    itemsReunited: 'شتە ڕادەستکراوەکان',
    members: 'ئەندامەکان',
    activeListings: 'لیستە چالاکەکان',
    reunionRate: 'ڕێژەی گەڕانەوە',
    realReunions: 'گەڕانەوەی ڕاستەقینە، دڵنیایی ڕاستەقینە',
    peopleReconnect: 'خەڵکی پەیوەندی دەکەنەوە بەو شتانەی پێیانوابوو بۆ هەمیشە لەدەستچوون.',
    isDozerFree: 'ئایا بێدۆزە بەخۆڕاییە؟',
    isDozerFreeDesc: 'بەڵی، ڕاپۆرتکردنی شتە ونبووەکان و دۆزراوەکان و پەیوەندیکردن بە تەواوی بێبەرامبەرە. پاداشتەکان ئارەزوومەندانەن.',
    howKeepSafe: 'چۆن زانیارییەکانم دەپارێزیت؟',
    howKeepSafeDesc: 'پەنا بەستراوە بە سیستەمی پێشکەوتو و پاراستنی تایبەتمەندی بۆ دڵنیابوون لەوەی زانیارییەکانت پارێزراون.',
    whatDoBefore: 'چۆن بەر لە ملاقاتکردنی کەسێک ماڵ؟',
    whatDoBeforeDesc: 'هەمووکات لە شوێنێکی گشتی و ڕووناکدا یەکتر ببینن و وردەکارییەکان بپشکنن.',
    lostSomethingTitle: 'شتێکت ون بووە؟ با بینێرینەوە بۆ ماڵەوە.',
    lostSomethingSubtitle: 'بەشداری لە کۆمەڵگەیەک بکە کە باوەڕی بە گەڕاندنەوەی شتەکان هەیە. یەکەم ڕاپۆرتی خۆت لە کەمتر لە خولەکێکی دەوێت.',
    reportAnItem: 'ڕاپۆرتی شتێك',
    browseItems: 'گەڕان بە شتەکاندا',
    footerTagline: 'ڕێگەی متمانەپێکراو بۆ کۆکردنەوەی خەڵک لەگەڵ ئەوەی ونیان کردووە — بە هاوکاری کۆمەڵگە.',
    product: 'بەرهەم',
    company: 'کۆمپانیا',
    faq: 'پرسیارە باوەکان',
    about: 'دەربارە',
    careers: 'هەلی کار',
    allRightsReserved: '© ٢٠٢٦ بێدۆزە. هەموو مافەکان پارێزراون.',

    faqTitle: 'پرسیارەکان، وەڵام دراونەتەوە',
    faqSubtitle: 'هەموو ئەوەی پێویستە بۆ دڵنیابوون لە بەکارهێنانی بێدۆزە.',
    howItWorksTitle: 'چوار هەنگاوی ساده بۆ کۆتاییەکی خۆش',
    howItWorksSubtitle: 'بەبێ ماندووبوون لەگەڵ هەژمارەکان — تەنها ڕێگەیەکی ڕوون لە ونبوو بۆ دۆزراوە.',
    step1Title: 'ڕاپۆرتی بکە',
    step1Desc: 'وێنەیەک و چەند وردەکارییەک زیاد بکە. کەمتر لە خولەکێکی دەوێت.',
    step2Title: 'گونجان بدۆزەوە',
    step2Desc: 'سیستەمەکەمان هاوشێوە ئەگەرییەکان بە خێرایی دەدۆزێتەوە.',
    step3Title: 'بە سەلامەتی پەیوەندی بکە',
    step3Desc: 'بۆ دڵنیابوون لە خاوەندارێتی پێش یەکتربینین بە ئارامی قسە بکەن.',
    step4Title: 'یەکتربینینەوە',
    step4Desc: 'ڕادەستکردن ڕێکخە و بە چارەسەرکراو تۆماری بکە. هەمووان سەرکەوتوون.',

    catElectronics: 'ئەلکترۆنیات',
    catElectronicsDesc: 'تەلەفۆن، لپتۆپ، گوێبیست',
    catWallets: 'جزدان و کارتەکان',
    catWalletsDesc: 'جزدان، جانتای کچان، کارتەکان',
    catKeys: 'کلیلەکان',
    catKeysDesc: 'کلیلەکانی ماڵ و ئۆتۆمبیل',
    catBags: 'جانتایل و سندوق',
    catBagsDesc: 'پشتیوان، جانتای گەشت',
    catJewelry: 'خشڵ و زێڕ',
    catJewelryDesc: 'ئەڵقە، سەعات، ملوانکە',
    catDocuments: 'بەڵگەنامەکان',
    catDocumentsDesc: 'ناسنامە، پاسپۆرت، كاغەز',
    catPets: 'ئاژەڵە ماڵییەکان',
    catPetsDesc: 'سەگ، پشیلە و هاوڕێکان',
    catClothing: 'جلوبەرگ',
    catClothingDesc: 'کۆات، کڵاو، تەوقە',
    catAccessories: 'پێداویستییەکان',
    catAccessoriesDesc: 'چاویلکە، چەتر',
    catOther: 'هی تر',
    catOtherDesc: 'هەموو شتێکی تر',

    badgeLost: 'ونبوو',
    badgeFound: 'دۆزراوە',
    faqSmartMatch: 'گونجاندنی زیرەک چۆن کار دەکات؟',
    faqSmartMatchDesc: 'سیستەمەکەمان بەراوردی وشە، بەروار و شوێنەکان دەکات بۆ دۆزینەوەی باشترین گونجان.',
    faqReward: 'ئایا دەتوانم پاداشت دابنێم؟',
    faqRewardDesc: 'بەڵێ! دەتوانیت بڕێک پاداشت دیاری بکەیت بۆ هاندانی خەڵک بۆ گەڕاندنەوەی خێرا.',
    story1Quote: 'جانتای لاپتۆپەکەم لە نزیک زانکۆ لە هەولێر بەجێهێشت و شڵەژام. محەمەد سابیر یارمەتیدام لە ماوەی کەمتر لە کاتژمێرێکدا بیدۆزمەوە.',
    story1Name: 'ئازاد ئارام',
    story1Detail: 'گەڕاندنەوەی کەلوپەل • هەولێر',
    story2Quote: 'مۆڵەتی شۆفێرییەکی ونبووم لە سەر شەقامێکی سلێمانی دۆزیەوە. لە ڕێگەی پلاتفۆرمەکەوە، هەمان ڕۆژ بە سەلامەتی گەڕاندمانەوە بۆ خاوەنەکەی.',
    story2Name: 'ئاکام عەلی',
    story2Detail: 'گەڕاندنەوەی ناسنامە • سلێمانی',
    story3Quote: 'فلاشێکی داتاکانی پڕۆژەکەمان لە نزیک کتێبخانە ونکرد. ئارێز، ئاکام، و زینا یارمەتیان داین و بە خێرایی دۆزیمانەوە.',
    story3Name: 'زینا عەبدوڵا',
    story3Detail: 'گەڕاندنەوەی داتای پڕۆژە • دهۆک',

    backHome: 'گەڕانەوە بۆ سەرەتا',
    createAccountTitle: 'هەژمار دروست بکە',
    createAccountSubtitle: 'بەشداری لە بێدۆزە بکە بۆ ڕاپۆرتکردن و دۆزینەوەی شتە ونبووەکان',
    orContinueWithEmail: 'یان بە ئیمەیڵ بەردەوام بە',
    fullName: 'ناوی تەواو',
    email: 'ئیمەیڵ',
    password: 'وشەی نهێنی',
    createAccountBtn: 'دروستکردنی هەژمار',
    alreadyHaveAccount: 'پێشتر هەژمارت هەەیە؟',
    rightSideTitle: 'بەشداری لە کۆمەڵگەیەک بکە کە شتەکان دەگەڕێنێتەوە مالەوە.',
    smartMatching: 'گونجاندنی زیرەک',
    smartMatchingDesc: 'دۆزینەوەی خێرای هاوشێوەکان',
    privateSecure: 'تایبەت و سەلامەت',
    privateSecureDesc: 'زانیارییەکانت بۆ خۆت دەمێننەوە',
    trustedCommunity: 'کۆمەڵگەی متمانەپێکراو',
    trustedCommunityDesc: '١٢٦ هەزار+ ئەندامی پشتڕاستکراوە',
    welcomeBack: 'بەخێراییەتەوە',
    loginSubtitle: 'چوونەژوورەوە بۆ بەڕێوەبردنی ڕاپۆرت و نامەکانت.',
    orContinueEmail: 'یان بە ئیمەیڵ بەردەوام بە',
    forgotPassword: 'وشەی نهێنیت بیرچووە؟',
    signInBtn: 'چوونەژوورەوە',
    magicLink: 'لە جێی ئەوە بە ستەری جادویی بنێره',
    newHere: 'تازەیت؟',
    createAccountLink: 'هەژمار دروست بکە',
    loginRightTitle: 'شتێکت ون بووە؟ تەنها یەک هەنگاو ماوە بۆ گەڕاندنەوەی.',

    // Kurdish Search & Filters:
    searchPageTitle: 'گەڕان بەدوای شتەکاندا',
    searchPageSubtitle: 'پاڵاوتن بەپێی جۆر، پۆل و وشە سەرەکییەکان بۆ دۆزینەوەی ئەوەی دەگەڕێیت بەدوایدا',
    searchInputPlaceholder: 'گەڕان بەپێی ناونیشان، براند، شوێن، وشەی سەرەکی',
    allCategories: 'هەموو پۆلەکان',
    allTypes: 'هەموو شتەکان',
    mostRecent: 'نوێترین',
    clearFilters: 'پاککردنەوەی پاڵاوتنەکان',
    noMatchingItems: 'هیچ شتێکی هاوشێوە نەدۆزرایەوە',
    tryAdjustingFilters: 'هەوڵ بدە پاڵاوتنەکان یان وشەکانی گەڕان بگۆڕیت',
    itemNotFound: 'شتەکە نەدۆزرایەوە',
itemNotFoundDesc: 'ئەو شتەی بەدوایدا دەگەڕێیت بوونی نییە یان سڕاوەتەوە.',
goBackSearch: 'گەڕانەوە بۆ گەڕان',
mustBeSignedIn: 'پێویستە بچیتە ژوورەوە',
sendSecureMessage: 'نامەیەکی پارێزراو بنێرە',
introduceYourself: 'خۆت بناسێنە و ڕوونی بکەرەوە چۆن دەتوانیت یارمەتیدەر بیت.',
shareDetailsTip: 'ئامۆژگاری: تەنها ئەو وردەکارییانە بڵێ کە خاوەنی ڕاستەقینە دەیزانێت بۆ سەلماندنی خاوەندارێتی.',
messagePlaceholder: 'سڵاو، پێموایە ئەمە هی من بێت...',
sendMessageBtn: 'ناردنی نامە',
home: 'سەرەتا',
views: 'بینین',
description: 'وردەکارییەکان',
category: 'پۆل',
dateLostStr: 'بەرواری ونبوون',
dateFoundStr: 'بەرواری دۆزینەوە',
colour: 'ڕەنگ',
ownerStr: 'خاوەن',
reports: 'ڕاپۆرتەکان',
helpful: 'بەسوود',
contactBtn: 'پەیوەندی بکە بە',
saveBtn: 'پاشەکەوت',
locationStr: 'شوێن',
clickForDirections: 'بۆ نەخشە کلیک بکە',
country: 'وڵات',
city: 'شار',
signInToSave: 'بچۆ ژوورەوە بۆ پاشەکەوتکردن',
oldest: 'کۆنترین',
searching: 'گەڕان...',
itemsFound: 'شت دۆزرایەوە',
itemFound: 'شت دۆزرایەوە',
reward: 'پاداشت',
justNow: 'هەر ئێستا',
unknownLocation: 'شوێنی نەزانراو',
  },
  'Arabic': {
    lostItems: 'العناصر المفقودة',
    foundItems: 'العناصر المعثورة',
    howItWorks: 'كيف يعمل',
    successStories: 'قصص النجاح',
    signIn: 'تسجيل الدخول',
    getStarted: 'ابدأ الان',
    heroTitle: 'نعيذك إلى ما يهمك أكثر',
    heroSubtitle: 'أكثر شبكة تطوراً للمفقودات والموجودات. سريعة وآمنة ومصممة بدقة للاكتشاف الحديث.',
    reportLost: 'أبلغ عن غرض مفقود',
    foundSomething: 'وجدت شيئاً',
    searchPlaceholder: 'ابحث عن غرض مفقود أو موجود...',
    searchButton: 'بحث',
    browseCategory: 'تصفح حسب الفئة',
    whatAreYouLookingFor: 'عَمَّ تبحث؟',
    jumpStraight: 'انتقل مباشرة إلى الفئة التي تطابق غرضك.',
    viewAll: 'تصفح الكل',
    recentlyFound: 'مفقودات حديثة',
    oneOfTheseYours: 'ساعد في إعادة هذه الأغراض',
    kindPeople: 'شخص ما يأمل في إيجادها. عمل صغير يمكن أن يحدث فرقاً كبيراً.',
    itemsReunited: 'أغراض أُعِيدت',
    members: 'الأعضاء',
    activeListings: 'قوائم نشطة',
    reunionRate: 'نسبة الاسترجاع',
    realReunions: 'قصص نجاح',
    peopleReconnect: 'إليك ما يقوله مستخدمونا عن تجربة استخدام Bdozawa.',
    isDozerFree: 'Bdozawa مجاني الاستخدام؟',
    isDozerFreeDesc: 'نعم، الإبلاغ عن المفقودات أو الموجودات والتواصل مع الناس مجاني تماماً. المكافآت اختيارية ويحددها من فقد الغرض.',
    howKeepSafe: 'كيف تحمي معلوماتي؟',
    howKeepSafeDesc: 'نحن نستخدم أحدث تقنيات التشفير والخصوصية لحماية تفاصيل اتصالك.',
    whatDoBefore: 'ماذا أفعل قبل مقابلة شخص ما؟',
    whatDoBeforeDesc: 'التق دائماً في مكان عام ومضاء جيداً وتحقق من التفاصيل.',
    lostSomethingTitle: 'فقدت شيئاً؟ دعنا نعيده إلى البيت.',
    lostSomethingSubtitle: 'انضم إلى مجتمع يؤمن بإعادة الأشياء. انشر إعلانك الأول في أقل من دقيقة.',
    reportAnItem: 'أبلغ عن غرض',
    browseItems: 'تصفح الأغراض',
    footerTagline: 'الطريقة الأكثر موثوقية لمساعدة الناس في استعادة ما فقدوه - مدعومة بالمجتمع والبحث الذكي.',
    product: 'المنتج',
    company: 'الشركة',
    faq: 'الأسئلة الشائعة',
    about: 'حول',
    careers: 'وظائف',
    allRightsReserved: '© 2026 Bdozawa. جميع الحقوق محفوظة.',

    faqTitle: 'أسئلة مع إجاباتها',
    faqSubtitle: 'كل ما تحتاجه لتشعر بالثقة عند استخدام Bdozawa.',
    howItWorksTitle: 'أربع خطوات بسيطة لنهاية سعيدة',
    howItWorksSubtitle: 'بلا تعقيدات أو حسابات مزعجة — مسار واضح من الضياع إلى العثور.',
    step1Title: 'أبلغ عن الغرض',
    step1Desc: 'أضف صورة وبعض التفاصيل. يستغرق أقل من دقيقة.',
    step2Title: 'احصل على تطابق',
    step2Desc: 'يقوم نظامنا بعرض التطابقات المحتملة بدرجة ثقة.',
    step3Title: 'تواصل بأمان',
    step3Desc: 'دردش بأمان للتحقق من الملكية قبل اللقاء.',
    step4Title: 'أعد الغرض',
    step4Desc: 'رتب موعد التسليم واجعله محلولاً. الجميع يربح.',

    catElectronics: 'إلكترونيات',
    catElectronicsDesc: 'هواتف، أجهزة حاسوب، سماعات',
    catWallets: 'محافظ وبطاقات',
    catWalletsDesc: 'محافظ، حقائب يد، بطاقات',
    catKeys: 'مفاتيح',
    catKeysDesc: 'مفاتيح منزل وسيارة',
    catBags: 'حقائب وأمتعة',
    catBagsDesc: 'حقائب ظهر، حقائب سفر',
    catJewelry: 'مجوهرات',
    catJewelryDesc: 'خواتم، ساعات، قلائد',
    catDocuments: 'مستندات',
    catDocumentsDesc: 'هويات، جوازات سفر، أوراق',
    catPets: 'حيوانات أليفة',
    catPetsDesc: 'كلاب، قطط ورفاق',
    catClothing: 'ملابس',
    catClothingDesc: 'سترات، قبعات، أوشحة',
    catAccessories: 'إكسسوارات',
    catAccessoriesDesc: 'نظارات، مظلات',
    catOther: 'أخرى',
    catOtherDesc: 'كل ما عدا ذلك',

    badgeLost: 'مفقود',
    badgeFound: 'موجود',
    faqSmartMatch: 'كيف يعمل التطابق الذكي؟',
    faqSmartMatchDesc: 'يقوم محركنا بعرض التطابقات المحتملة من خلال مقارنة الكلمات الرئيسية والتواريخ والمواقع.',
    faqReward: 'هل يمكنني تقديم مكافأة؟',
    faqRewardDesc: 'نعم! يمكنك اختيارياً إرفاق مبلغ مكافأة عند الإبلاغ عن غرض مفقود لتشجيع الإعادة السريعة.',
    story1Quote: 'تركت حقيبة حاسوبي المحمول بالقرب من الجامعة في أربيل. ساعدني محمد صابر في تتبعها عبر Bdozawa في غضون ساعة.',
    story1Name: 'آزاد آرام',
    story1Detail: 'استعادة معدات • أربيل',
    story2Quote: 'وجدت رخصة قيادة مفقودة في السليمانية. باستخدام المنصة، أعدناها بأمان إلى مالكها في نفس اليوم.',
    story2Name: 'آكام علي',
    story2Detail: 'إعادة هوية • السليمانية',
    story3Quote: 'فقدنا قرصاً مدمجاً يحتوي على بيانات مشروعنا. ساعدنا آريز وآكام وزينا في استعادته على الفور.',
    story3Name: 'زينا عبد الله',
    story3Detail: 'استعادة بيانات مشروع • دهوك',

    backHome: 'العودة للرئيسية',
    createAccountTitle: 'إنشاء حساب',
    createAccountSubtitle: 'انضم إلى Bdozawa للإبلاغ عن العناصر المفقودة والعثور عليها',
    orContinueWithEmail: 'أو المتابعة بريد الإلكتروني',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    createAccountBtn: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    rightSideTitle: 'انضم إلى المجتمع الذي يعيد الأشياء إلى منازلها.',
    smartMatching: 'تطابق ذكي',
    smartMatchingDesc: 'ابحث عن التطابقات المحتملة على الفور',
    privateSecure: 'خاص وآمن',
    privateSecureDesc: 'تفاصيلك تبقى ملكاً لك',
    trustedCommunity: 'مجتمع موثوق',
    trustedCommunityDesc: 'أكثر من 126 ألف عضو معتمد',
    welcomeBack: 'مرحباً بك مجدداً',
    loginSubtitle: 'تسجيل الدخول لإدارة قوائمك ورسائلك.',
    orContinueEmail: 'أو المتابعة بريد الإلكتروني',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    signInBtn: 'تسجيل الدخول',
    magicLink: 'أرسل لي رابطاً سحرياً بدلاً من ذلك',
    newHere: 'جديد هنا؟',
    createAccountLink: 'انشئ حساباً',
    loginRightTitle: 'فقدت شيئاً؟ أنت على بعد خطوة واحدة من استعادته.',

    // Arabic Search & Filters:
    searchPageTitle: 'البحث عن العناصر',
    searchPageSubtitle: 'التصفية حسب النوع والفئة والكلمات الرئيسية للعثور على ما تبحث عنه',
    searchInputPlaceholder: 'البحث بالعنوان، العلامة التجارية، الموقع، الكلمة الرئيسية',
    allCategories: 'جميع الفئات',
    allTypes: 'جميع العناصر',
    mostRecent: 'الأحدث',
    clearFilters: 'مسح عوامل التصفية',
    noMatchingItems: 'لا توجد عناصر مطابقة',
    tryAdjustingFilters: 'جرب ضبط عوامل التصفية أو مصطلحات البحث',
    itemNotFound: 'العنصر غير موجود',
itemNotFoundDesc: 'العنصر الذي تبحث عنه غير موجود أو تمت إزالته.',
goBackSearch: 'العودة للبحث',
mustBeSignedIn: 'يجب تسجيل الدخول',
sendSecureMessage: 'إرسال رسالة آمنة',
introduceYourself: 'قدم نفسك واشرح كيف يمكنك المساعدة.',
shareDetailsTip: 'نصيحة: شارك فقط التفاصيل التي يعرفها المالك الحقيقي لإثبات الملكية.',
messagePlaceholder: 'مرحباً، أعتقد أن هذا قد يكون لي...',
sendMessageBtn: 'إرسال رسالة',
home: 'الرئيسية',
views: 'مشاهدة',
description: 'الوصف',
category: 'الفئة',
dateLostStr: 'تاريخ الفقدان',
dateFoundStr: 'تاريخ العثور',
colour: 'اللون',
ownerStr: 'المالك',
reports: 'التقارير',
helpful: 'مفيد',
contactBtn: 'تواصل مع',
saveBtn: 'حفظ',
locationStr: 'الموقع',
clickForDirections: 'انقر للاتجاهات',
country: 'الدولة',
city: 'المدينة',
signInToSave: 'تسجيل الدخول لحفظ القوائم',
oldest: 'الأقدم',
searching: 'جاري البحث...',
itemsFound: 'عناصر تم العثور عليها',
itemFound: 'عنصر تم العثور عليه',
reward: 'مكافأة',
justNow: 'الآن',
unknownLocation: 'موقع غير معروف',
  }
};

const ThemeLanguageContext = createContext<ThemeLanguageContextType | undefined>(undefined);

export const ThemeLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('English');
  const [theme, setTheme] = useState<Theme>('dark');

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const dir = (language === 'Kurdish (Sorani)' || language === 'Arabic') ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.style.backgroundColor = theme === 'dark' ? '#0d1117' : '#ffffff';
    document.documentElement.style.color = theme === 'dark' ? '#ffffff' : '#111827';
  }, [dir, theme]);

  const t = (key: string): string => {
    const text = translations[language][key] || key;
    // Enforce BiDi directional isolation to fix period/punctuation inversion in RTL views
    if (dir === 'rtl') {
      return `\u2066${text}\u2069`;
    }
    return text;
  };

  return (
    <ThemeLanguageContext.Provider value={{ language, setLanguage, theme, toggleTheme, t, dir }}>
      {children}
    </ThemeLanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useThemeLanguage = () => {
  const context = useContext(ThemeLanguageContext);
  if (!context) {
    throw new Error('useThemeLanguage must be used within a ThemeLanguageProvider');
  }
  return context;
};

export default ThemeLanguageContext;